# AKING0v0的「Clash_Config」配置
# 现配置作者：https://github.com/AKING0v0
# 原配置作者：https://github.com/Rabbit-Spec
# 核心设置保留原版 Clash_Max，策略与规则修改自 ACL4SSR
# 适用版本：所有使用 Mihomo (Meta) 内核的程序

port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894

unified-delay: true
geodata-mode: true
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: true
mode: rule
log-level: info
ipv6: false
udp: true

external-controller: 0.0.0.0:9090

geox-url:
  mmdb: 'https://geodata.kelee.one/Country-Masaiki.mmdb'
  asn: 'https://geodata.kelee.one/GeoLite2-ASN-P3TERX.mmdb'
  geosite: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat' 
  geoip: 'https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat'

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - '+.mi.com'                  
    - '+.apple.com'               # 如果 Windows 上装了 iCloud 或 Apple Music 必加
    - '+.push.apple.com'
    # --- 针对 Windows 及游戏优化 ---
    - '+.msftconnecttest.com'     # 微软网络探测
    - '+.msftncsi.com'
    - '+.stun.*'                  # 放行所有 STUN 流量，大幅改善游戏语音和 UDP 联机
    - '+.stun.*.*'
    - '+.stun.*.*.*'

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true

listeners:
- name: socks5-in-1
  type: socks
  port: 10808
  listen: 0.0.0.0
  udp: true
  users: []
  proxy: DIRECT

dns:
  enable: true
  prefer-h3: false
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '+.lan'
    - '+.local'
    - 'localhost.ptlogin2.qq.com'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.stun.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'

  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29

  nameserver-policy:
    'geosite:cn,private':
      - https://223.5.5.5/dns-query
      - https://223.6.6.6/dns-query

  nameserver:
    - https://8.8.8.8/dns-query
    - https://1.1.1.1/dns-query

# 锚点 - 节点订阅的参数
NodeParam: &NodeParam {type: http, interval: 21600, health-check: {enable: true, url: 'http://www.gstatic.com/generate_204', interval: 120}}

# 【新增】锚点 - 全局机场名单 (在这里管理所有机场的名字)
# 以后有新机场，只需要在这里加上名字，并在下方 proxy-providers 添加对应配置即可
AllProviderList: &AllProviderList [机场订阅1,机场订阅2]

proxy-providers: 
  机场订阅1:
    url: '机场订阅链接1'
    <<: *NodeParam
    path: './proxy_provider/Providers_1.yaml'
  机场订阅2:
    url: '机场订阅链接2'
    <<: *NodeParam
    path: './proxy_provider/Providers_2.yaml'

# 锚点
# 地区筛选正则
FilterAI: &FilterAI "(?i)(🇯🇵|🇸🇬|🇹🇼|🇰🇷|🇺🇸|日本|东京|大阪|新加坡|狮|台湾|韩国|韓|首尔|美国|洛杉矶|旧金山|圣何塞|西雅图|波特兰|\\b(JP|JPN|Japan|SG|SGP|Singapore|TW|TWN|Tai|Taiwan|KR|KOR|Korea|US|USA|United States)\\d*\\b)"
FilterTikTok: &FilterTikTok "(?i)(🇯🇵|🇸🇬|🇹🇼|🇰🇷|🇺🇸|日本|东京|大阪|新加坡|狮|台湾|韩国|韓|首尔|美国|洛杉矶|旧金山|圣何塞|西雅图|波特兰|\\b(JP|JPN|Japan|SG|SGP|Singapore|TW|TWN|Tai|Taiwan|KR|KOR|Korea|US|USA|United States)\\d*\\b)"
FilterHK: &FilterHK "^(?=.*(?i)(🇭🇰|香港|\\b(HK|HKG|Hong)\\d*\\b))(?!.*(?i)(0\\.\\d+|1\\.[1-9]\\d*|[2-9](\\.\\d+)?|\\d{2,})[xX倍]).*$"
FilterJP: &FilterJP "(?i)(🇯🇵|日本|东京|大阪|\\b(JP|JPN|Japan)\\d*\\b)"
FilterTW: &FilterTW "(?i)(🇹🇼|台湾|\\b(TW|TWN|Tai|Taiwan)\\d*\\b)"
FilterKR: &FilterKR "(?i)(🇰🇷|韩国|韓|首尔|\\b(KR|KOR|Korea)\\d*\\b)"
FilterSG: &FilterSG "(?i)(🇸🇬|新加坡|狮|\\b(SG|SGP|Singapore)\\d*\\b)"
FilterUS: &FilterUS "(?i)(🇺🇸|美国|洛杉矶|旧金山|圣何塞|西雅图|波特兰|\\b(US|USA|United States)\\d*\\b)"
FilterGlobal: &FilterGlobal "^(?!.*(?i)(群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|超时|收藏|\\b(USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|Traffic)\\d*\\b|\\d{4}-\\d{2}-\\d{2}|\\dG)).*$"

# 自动测速组参数 (url-test)
AutoTest: &AutoTest {type: url-test, url: 'http://www.gstatic.com/generate_204', interval: 120, tolerance: 60}

proxy-groups:
  - name: ✈️ 起飞选择
    type: select
    proxies: [♻️ 故障转移, ⚡ 最低延迟, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇺🇲 美国节点, 👆🏻 手动切换]

  - name: 🐟 漏网之鱼
    type: select
    proxies: [✈️ 起飞选择, DIRECT, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇺🇲 美国节点, 👆🏻 手动切换]

  - name: ♻️ 故障转移
    type: fallback
    url: 'http://www.gstatic.com/generate_204'
    interval: 120
    tolerance: 60
    proxies: [🇭🇰 香港节点, 🇯🇵 日本节点, 🇨🇳 台湾节点]

  - name: 👆🏻 手动切换
    type: select
    proxies: [🌏 其他国家]
    use: *AllProviderList
    filter: '.*'

  - name: ⚡ 最低延迟
    <<: *AutoTest
    use: *AllProviderList
    # 逻辑：匹配任意字符，且不包含排除关键字
    filter: *FilterGlobal

  - name: 💬 Ai平台
    type: select
    proxies: [🇯🇵 日本节点, 🇨🇳 台湾节点, 🇺🇲 美国节点]

  - name: 📹 油管视频
    type: select
    proxies: [✈️ 起飞选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇨🇳 台湾节点, 🇺🇲 美国节点, 👆🏻 手动切换]

  - name: 🎵 TikTok
    type: select
    proxies: [✈️ 起飞选择]
    use: *AllProviderList
    filter: *FilterTikTok

  - name: 📲 电报消息
    type: select
    proxies: [✈️ 起飞选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇨🇳 台湾节点, 🇺🇲 美国节点, 👆🏻 手动切换]

  - name: 📺 哔哩哔哩
    type: select
    proxies: [DIRECT, 🇭🇰 香港节点, 🇨🇳 台湾节点]

  - name: 🎓 学术平台
    type: select
    proxies: [DIRECT, 👆🏻 手动切换]

  - name: 🪟 微软服务
    type: select
    proxies: [DIRECT, 👆🏻 手动切换]

  - name: 🍎 苹果服务
    type: select
    proxies: [DIRECT, 👆🏻 手动切换]

  - name: 🎯 全球直连
    type: select
    proxies: [DIRECT, 👆🏻 手动切换]

  - name: 🌏 其他国家
    type: select
    use: *AllProviderList
    # 逻辑：排除CN,HK,TW,SG,JP,US,KR
    filter: '^(?!.*(?i)(🇨🇳|🇭🇰|🇹🇼|🇸🇬|🇯🇵|🇺🇸|🇰🇷|中国|香港|台湾|新加坡|狮|日本|东京|大阪|美国|洛杉矶|圣何塞|西雅图|波特兰|韩国|韓|首尔|\b(CN|China|HK|HKG|Hong|TW|TWN|Tai|Taiwan|SG|SGP|Singapore|JP|JPN|Japan|US|USA|United States|KR|KOR|Korea)\d*\b)).*$'

  - name: 🇭🇰 香港节点
    <<: *AutoTest
    use: *AllProviderList
    filter: *FilterHK
  
  - name: 🇯🇵 日本节点
    <<: *AutoTest
    use: *AllProviderList
    filter: *FilterJP

  - name: 🇨🇳 台湾节点
    <<: *AutoTest
    use: *AllProviderList
    filter: *FilterTW

  - name: 🇰🇷 韩国节点
    <<: *AutoTest
    use: *AllProviderList
    filter: *FilterKR
  
  - name: 🇸🇬 狮城节点
    <<: *AutoTest
    use: *AllProviderList
    filter: *FilterSG
  
  - name: 🇺🇲 美国节点
    <<: *AutoTest
    use: *AllProviderList
    filter: *FilterUS
 
# 规则集定义
# 注意：由于源是 .list 格式，behavior 设为 classical
RuleSetClassical: &RuleSetClassical {type: http, behavior: classical, interval: 86400, format: text}

rule-providers:
  Lan:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Lan/Lan.list
    path: ./ruleset/Lan.list

  Download:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Download/Download.list
    path: ./ruleset/Download.list

  GoogleCN:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
    path: ./ruleset/GoogleCN.list

  SteamCN:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.list
    path: ./ruleset/SteamCN.list

  AiSuite:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/dler-io/Rules/refs/heads/main/Surge/Surge%203/Provider/AI%20Suite.list
    path: ./ruleset/AiSuite.list

  Microsoft:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
    path: ./ruleset/Microsoft.list

  Apple:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
    path: ./ruleset/Apple.list

  Google:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
    path: ./ruleset/Google.list

  GitHub:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
    path: ./ruleset/GitHub.list

  Telegram:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list
    path: ./ruleset/Telegram.list

  YouTube:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
    path: ./ruleset/YouTube.list

  TikTok:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
    path: ./ruleset/TikTok.list

  BiliBiliHMT:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
    path: ./ruleset/BiliBiliHMT.list
  
  BiliBiliBM:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/BiliBili/BiliBili.list
    path: ./ruleset/BiliBiliBM.list

  Proxy:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Proxy/Proxy.list
    path: ./ruleset/Proxy.list

  Scholar:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Scholar/Scholar.list
    path: ./ruleset/Scholar.list

  China:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list
    path: ./ruleset/China.list

  Direct:
    <<: *RuleSetClassical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Direct/Direct.list
    path: ./ruleset/Direct.list

rules:
  # 局域网及个人最高优先级覆盖（必须放在最前）
  - RULE-SET,Lan,🎯 全球直连

  # 境内高频下载与特例服务直连（防止被后续的 Proxy 规则捕获）
  - RULE-SET,Download,🎯 全球直连
  - RULE-SET,GoogleCN,🎯 全球直连
  - RULE-SET,SteamCN,🎯 全球直连

  # 指定服务及平台精准分流（必须放在 Proxy 泛用规则之前）
  - RULE-SET,AiSuite,💬 Ai平台
  - RULE-SET,Microsoft,🪟 微软服务
  - RULE-SET,Apple,🍎 苹果服务
  - RULE-SET,Google,✈️ 起飞选择
  - RULE-SET,GitHub,✈️ 起飞选择
  - RULE-SET,Telegram,📲 电报消息
  - RULE-SET,YouTube,📹 油管视频
  - RULE-SET,TikTok,🎵 TikTok

  # 哔哩哔哩分流
  - RULE-SET,BiliBiliHMT,📺 哔哩哔哩
  - RULE-SET,BiliBiliBM,📺 哔哩哔哩

  # 广泛的代理规则兜底
  - RULE-SET,Proxy,✈️ 起飞选择
  
  - RULE-SET,Scholar,🎓 学术平台

  # 中国大陆域名及直连兜底
  - RULE-SET,China,🎯 全球直连
  - RULE-SET,Direct,🎯 全球直连
  
  # 🎯 全球直连 - GEOIP CN
  - GEOIP,CN,🎯 全球直连
  
  # 🐟 漏网之鱼 - Final
  - MATCH,🐟 漏网之鱼
