# AKING0v0的「Clash_Config」Mihomo配置
# 现配置作者：https://github.com/AKING0v0
# 原配置作者：https://github.com/Rabbit-Spec
# 适用版本：所有使用 Mihomo (Meta) 内核的程序，OpenClash使用按需修改

# 全局网络与基础设置
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 7893
tproxy-port: 7894
allow-lan: true
mode: rule
log-level: info
ipv6: false
tcp-concurrent: true
unified-delay: true
# 进程匹配模式（OpenClash 环境下设为 off）
find-process-mode: strict

# 面板与外部控制
external-controller: 0.0.0.0:9090

# 数据库与配置文件存储
geox-url:
  mmdb: https://testingcf.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/lite/Country.mmdb
  geoip: https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  asn: https://testingcf.jsdelivr.net/gh/xishang0128/geoip@release/GeoLite2-ASN.mmdb
geo-auto-update: true
geo-update-interval: 24
geodata-mode: true
# GeoData 加载模式（内存容量有限路由器应设为 memconservative）
geodata-loader: standard

profile:
  store-selected: true
  store-fake-ip: true

# TUN 设置
tun:
  enable: true
  stack: system
  dns-hijack:
  - any:53
  endpoint-independent-nat: true
  # 自动配置路由表（OpenClash 环境下设为 false）
  auto-route: true
  # 自动检测网络接口（OpenClash 环境下设为 false）
  auto-detect-interface: true
  # 自动配置 iptables 重定向（OpenClash 环境下设为 false）
  auto-redirect: true
  # 严格路由模式（OpenClash 环境下应设为 false）
  strict-route: true
  disable-icmp-forwarding: false

# 流量嗅探设置
sniffer:
  enable: true
  override-destination: true
  sniff:
    QUIC:
      ports:
      - 443
    TLS:
      ports:
      - 443
      - 8443
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  skip-domain:
  - "+.mi.com"
  - "+.xiaomi.com"
  - "+.xiaomi.net"
  - "+.oray.com"
  - "+.sunlogin.net"
  - "+.push.apple.com"
  parse-pure-ip: true
  force-dns-mapping: true

# DNS 解析设置
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - "*.direct"
  - PDC._msDCS.*.*
  - DC._msDCS.*.*
  - GC._msDCS.*.*
  - cable.auth.com
  - network-test.debian.org
  - detectportal.firefox.com
  - resolver1.opendns.com
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - "*.cmpassport.com"
  - id6.me
  - open.e.189.cn
  - opencloud.wostore.cn
  - id.mail.wo.cn
  - mdn.open.wo.cn
  - hmrz.wo.cn
  - nishub1.10010.com
  - enrichgw.10010.com
  - "*.wosms.cn"
  - "*.jegotrip.com.cn"
  - "*.icitymobile.mobi"
  - "*.10099.com.cn"
  - "*.pingan.com.cn"
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  - "*.microdone.cn"
  - "+.qq.com"
  - "+.weixin.com"
  - "+.weixin.qq.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - stun.l.google.com
  - lens.l.google.com
  - na.b.g-tun.com
  - "+.mi.com"
  - "+.xiaomi.com"
  - "+.xiaomi.net"
  - "+.music.163.com"
  - "*.126.net"
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - "*.mcdn.bilivideo.cn"
  - "+.nflxvideo.net"
  - "+.media.dssott.com"
  - "*.blzstatic.cn"
  - "+.battle.net"
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - "+.srv.nintendo.net"
  - "+.cdn.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.uu.163.com"
  - ps.res.netease.com
  - "+.sandai.net"
  - "+.n0808.com"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - global.turn.twilio.com
  - global.stun.twilio.com
  - "+.pub.3gppnetwork.org"
  - injections.adguard.org
  - local.adguard.org
  respect-rules: false
  fake-ip-filter-mode: blacklist

# 锚点 - 节点订阅参数
NodeParam: &NodeParam {type: http, interval: 21600, health-check: {enable: true, url: 'https://www.gstatic.com/generate_204', interval: 300}}

# 锚点 - 全局机场名单 (在这里管理所有机场的名字)
# 以后有新机场，只需要在这里加上名字，并在下方 proxy-providers 添加对应配置即可
AllProviderList: &AllProviderList [机场订阅1,机场订阅2]

# 代理提供商
proxy-providers: 
  机场订阅1:
    url: '机场订阅链接1'
    <<: *NodeParam
    path: './proxy_provider/Providers_1.yaml'
  机场订阅2:
    url: '机场订阅链接2'
    <<: *NodeParam
    path: './proxy_provider/Providers_2.yaml'

# 锚点 - 地区筛选正则
FilterAi: &FilterAi '(?i)(🇯🇵|🇹🇼|🇰🇷|🇸🇬|🇺🇸|日|东京|大阪|台|韩|韓|首尔|坡|狮城|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|\b(JP|Japan|TW|Taiwan|KR|KOR|Korea|SG|Singapore|US|United States)\d*\b)'
FilterTikTok: &FilterTikTok '(?i)(🇯🇵|🇹🇼|🇰🇷|🇸🇬|🇺🇸|日|东京|大阪|台|韩|韓|首尔|坡|狮城|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|\b(JP|Japan|TW|Taiwan|KR|KOR|Korea|SG|Singapore|US|United States)\d*\b)'
FilterHK: &FilterHK '^(?=.*(?i)(🇭🇰|港|\b(HK|Hong Kong|HongKong)\d*\b))(?!.*(?i)(0\.\d+|1\.[1-9]\d*|[2-9](\.\d+)?|\d{2,})[xX倍]).*$'
FilterJP: &FilterJP '(?i)(🇯🇵|日|东京|大阪|\b(JP|Japan)\d*\b)'
FilterTW: &FilterTW '(?i)(🇹🇼|台|\b(TW|Taiwan)\d*\b)'
FilterKR: &FilterKR '(?i)(🇰🇷|韩|韓|首尔|\b(KR|KOR|Korea)\d*\b)'
FilterSG: &FilterSG '(?i)(🇸🇬|坡|狮城|\b(SG|Singapore)\d*\b)'
FilterUS: &FilterUS '(?i)(🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|\b(US|United States)\d*\b)'
FilterGlobal: &FilterGlobal '^(?!.*(?i)(群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|超时|收藏|\b(USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|Traffic)\d*\b|\d{4}-\d{2}-\d{2}|\dG)).*$'

# 锚点 - 自动测速组参数
AutoTest: &AutoTest {type: url-test, url: 'https://www.gstatic.com/generate_204', interval: 120, tolerance: 60}

# 策略组
proxy-groups:
- name: ✈️ 起飞选择
  type: select
  proxies: [♻️ 故障转移, ⚡ 最低延迟, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇺🇲 美国节点, 👆🏻 手动切换]

- name: 🐟 漏网之鱼
  type: select
  proxies: [✈️ 起飞选择, DIRECT, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇺🇲 美国节点, 👆🏻 手动切换]

- name: ♻️ 故障转移
  type: fallback
  url: 'https://www.gstatic.com/generate_204'
  proxies: [ 🇭🇰 香港节点, 🇯🇵 日本节点, 🇺🇲 美国节点]

- name: 👆🏻 手动切换
  type: select
  proxies: [🧊 冷门国家]
  use: *AllProviderList
  filter: '.*'

- name: ⚡ 最低延迟
  <<: *AutoTest
  use: *AllProviderList
  # 逻辑：匹配任意字符，且不包含排除关键字
  filter: *FilterGlobal

- name: 💬 Ai平台
  type: select

  proxies: [🇯🇵 日本节点, 🇨🇳 台湾节点, 🇺🇲 美国节点]
  use: *AllProviderList
  filter: *FilterAi

- name: 📲 电报消息
  type: select
  proxies: [✈️ 起飞选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇺🇲 美国节点]

- name: 📹 油管视频
  type: select
  proxies: [✈️ 起飞选择, 🇭🇰 香港节点, 🇯🇵 日本节点, 🇺🇲 美国节点]

- name: 🎵 TikTok
  type: select
  proxies: [✈️ 起飞选择, 🇨🇳 台湾节点, 🇺🇲 美国节点]
  use: *AllProviderList
  filter: *FilterTikTok

- name: 📺 哔哩哔哩
  type: select
  proxies: [DIRECT, 🇭🇰 香港节点, 🇨🇳 台湾节点]

- name: 🍎 苹果服务
  type: select
  proxies: [DIRECT, ✈️ 起飞选择]

- name: 🪟 微软服务
  type: select
  proxies: [DIRECT, ✈️ 起飞选择]

- name: 🎮 游戏平台
  type: select
  proxies: [DIRECT, ✈️ 起飞选择]

- name: 🎓 学术平台
  type: select
  proxies: [DIRECT, ✈️ 起飞选择]

- name: 🔀 非标端口
  type: select
  proxies: [DIRECT,🐟 漏网之鱼]

- name: 🎯 全球直连
  type: select
  proxies: [DIRECT]

- name: 🧊 冷门国家
  type: select
  use: *AllProviderList
  # 逻辑：排除CN,HK,TW,SG,JP,US,KR
  filter: '^(?!.*(?i)(🇨🇳|🇭🇰|🇹🇼|🇸🇬|🇯🇵|🇺🇸|🇰🇷|中国|香港|台湾|新加坡|狮|日本|东京|大阪|美国|洛杉矶|圣何塞|西雅图|波特兰|韩国|韓|首尔|\b(CN|China|HK|HKG|Hong|TW|TWN|Tai|Taiwan|SG|SGP|Singapore|JP|JPN|Japan|US|USA|United States|KR|KOR|Korea)\d*\b)).*$'

- name: 🇭🇰 香港节点
  <<: *AutoTest
  use: *AllProviderList
  filter: *FilterHK

- name: 🇯🇵 日本节点
  <<: *AutoTest
  use: *AllProviderList
  filter: *FilterJP

- name: 🇨🇳 台湾节点
  <<: *AutoTest
  use: *AllProviderList
  filter: *FilterTW

- name: 🇰🇷 韩国节点
  <<: *AutoTest
  use: *AllProviderList
  filter: *FilterKR

- name: 🇸🇬 狮城节点
  <<: *AutoTest
  use: *AllProviderList
  filter: *FilterSG

- name: 🇺🇲 美国节点
  <<: *AutoTest
  use: *AllProviderList
  filter: *FilterUS

# 规则集定义
RuleSetClassical: &RuleSetClassical {type: http, behavior: classical, interval: 86400}

# 规则提供商
rule-providers:
  Custom_Direct_Domain:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Domain.mrs
    path: ./ruleset/Custom_Direct_Domain.mrs

  Custom_Direct_IP:
    type: http
    behavior: ipcidr
    interval: 86400
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_IP.mrs
    path: ./ruleset/Custom_Direct_IP.mrs

  Custom_Proxy_Domain:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_Domain.mrs
    path: ./ruleset/Custom_Proxy_Domain.mrs

  Custom_Proxy_IP:
    type: http
    behavior: ipcidr
    interval: 86400
    format: mrs
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Proxy_IP.mrs
    path: ./ruleset/Custom_Proxy_IP.mrs

  PortDirect:
    <<: *RuleSetClassical
    url: https://testingcf.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Port_Direct.yaml
    path: ./ruleset/PortDirect.yaml

# 路由规则
rules:
# 私有域名及IP
- GEOSITE,private,🎯 全球直连
- GEOIP,private,🎯 全球直连,no-resolve

# 自定义规则
- RULE-SET,Custom_Direct_Domain,🎯 全球直连
- RULE-SET,Custom_Direct_IP,🎯 全球直连,no-resolve
- RULE-SET,Custom_Proxy_Domain,✈️ 起飞选择
- RULE-SET,Custom_Proxy_IP,✈️ 起飞选择,no-resolve

# 精准应用分流
- GEOSITE,category-ai-!cn,💬 Ai平台
- GEOSITE,category-games@cn,🎯 全球直连
- GEOSITE,category-games,🎮 游戏平台
- GEOSITE,github,✈️ 起飞选择
- GEOSITE,youtube,📹 油管视频
- GEOSITE,apple,🍎 苹果服务
- GEOSITE,microsoft,🪟 微软服务
- GEOSITE,tiktok,🎵 TikTok
- GEOSITE,bilibili,📺 哔哩哔哩
- GEOSITE,google,✈️ 起飞选择
- GEOSITE,telegram,📲 电报消息
- GEOSITE,category-scholar-!cn,🎓 学术平台
- GEOIP,google,✈️ 起飞选择,no-resolve
- GEOIP,telegram,📲 电报消息,no-resolve

# GFW 列表的域名走代理
- GEOSITE,gfw,✈️ 起飞选择
# 非中国大陆域名走代理
- GEOSITE,geolocation-!cn,✈️ 起飞选择

# GEO中国大陆直连兜底
- GEOSITE,cn,🎯 全球直连
- GEOIP,cn,🎯 全球直连,no-resolve

# 端口拦截
# 非标端口分流拦截放这里，确保只有常规网页端口漏网后才触发
- RULE-SET,PortDirect,🔀 非标端口

# 最终兜底
- MATCH,🐟 漏网之鱼
